### ISSUE TITLE
A question for n>2.

### ISSUE THREAD

**Issue by leqsxt** [georgekatona/Clique#1]
Dear georgekatona:
        Thank you for reading my commiment.I am a student of China I have read your code of clique line by line,and your code is very good, but i have a question can you solve it for me?
         In the function of insert_if_join_condition（）。I found it will find 2 repeated candidate dense units, while the n=3 or bigger. For example [[[0,1],[1,0]],[[0,1],[2,0]]] and [[[0,1],[1,0]],[[1,0],[2,0]] is a same dense unit but in your code the function of  insert_if_join_condition（）will generate two candidate.
         Maybe i have wrong understand og this issue,and can you address my question? If you can do this i wiil very appreciate about this.

**Comment by georgekatona** [comment]
Dear @leqsxt ,

Thank you for your comment, it really was the case that duplicated clusters could have been included in dimensions larger than 2. With [this commit](https://github.com/georgekatona/Clique/commit/0c9592d9c82239c949c630ebff741f63c29c8c46) it should be fixed, I also added a 3 dimensional test data file to check the results.

If you experience any further odd behaviour, please feel free to write.
